### ISSUE TITLE
Use colour variable instead of hard coded values

### ISSUE THREAD

**Issue by lordlycastle** [fisherman/dartfish#1]
Love the theme, but it's annoying the colour are hardcoded. It should use the colour variable such as `fish_color_command fish_color_cwd fish_color_*`, this way when a new user installs the theme, the colour scheme is still the same, only the prompt changes.

If we want best of both worlds, how about a global variable with which you can change between your colour scheme, and default one of the theme.

**Comment by lordlycastle** [comment]
I just noticed the `set_color_custom` function. What does that do?

**Comment by bucaran** [comment]
@lordlycastle Totally. And I'll fix it up as soon as I can unless you want to take a shot at it.

So, in my "vision", there are two kind of themes/prompts. Those that define their own colors, and those that use fish_color_* defaults.

I think dartfish should be exactly like the second option, but I rushed things and that's why it is not so currently.

Now, themes like [Superman](https://github.com/fishery/superman) or [Stark](https://github.com/fishery/stark) should define their own colors, since it would not make sense for them to be in any other color.

> I just noticed the set_color_custom function. What does that do?

That's a Fisherman specific function that allows you to customize fish syntax highlighting colors.

**Comment by bucaran** [comment]
> fish_color_command fish_color_cwd fish_color_*, this way when a new user installs the theme, the colour scheme is still the same, only the prompt changes.

Yes, this would be correct if `set_color_custom` didn't exist. Because this feature is available, what you are saying would not be a problem. Nevertheless, I think that in the case of Dartfish, it would be more appropriate if the prompt adapted to the user colors since there is nothing about the current colors that is intrinsic to dartfish.

**Comment by lordlycastle** [comment]
I can try to fix on the weekend. It should be as simple as replacing the colour values with variables, I imagine.

As for `set_color_custom`, is that just relevant when creating/editing new functions or using `fish_indent --ansi`? Shouldn't there be a way to reverse that? People might have custom highlighting as well, and they'd lose those setting.

**Comment by bucaran** [comment]
> I can try to fix on the weekend. It should be as simple as replacing the colour values with variables, I imagine.

Thanks. If nothing is done by then, please take a shot at it. I'll add you in a second.

> As for set_color_custom, is that just relevant when creating/editing new functions or using fish_indent --ansi? 

Nope. This is a function that runs only the first time you install the theme. 

> Shouldn't there be a way to reverse that? People might have custom highlighting as well, and they'd lose those setting.

When the function runs, fisherman saves the current colors and restores them when you uninstall it. So, no, users would not lose anything.

**Comment by lordlycastle** [comment]
I think we need to remove the `set_color_custom` because it's still overriding the user's syntax colours.

**Comment by bucaran** [comment]
Sure, if you don't want to use it, just remove it.

Also, we can close this as the original issue was fixed right?
